#!/bin/sh

if [ $# != 1 ];
then
    echo "usage: " $0 "<mysql_data_path>"
    exit 1
fi

dump_period=60

while :
do
    echo "=========================" `date` "========================="
    ./cdb_shm_dump $1 cdb_tab_dml
    sleep ${dump_period}
done
